Fix error when adding an unknown prefix
A subtest in https://github.com/web-platform-tests/wpt/blob/37cd0d66c1ef6b62142142fc2ea32f7fd7e1fbb9/domparsing/innerhtml-03.xhtml#L40 would cause the following error to be thrown during serialization:

InvalidStateError: Failed to serialize XML: Cannot read property 'push' of undefined

This resolves it by implementing step 2 of "To add a prefix" in https://w3c.github.io/DOM-Parsing/#dfn-add.